### PR TITLE
Refactor the gateway to properly accept close frames

### PR DESCRIPTION
**Pull request by kozabrada123**
also introduces a test for receiving the close codes. 

Differentiates the wasm and tungstenite gateways a bit more.

The same thing should be done for the voice gateway, I'll likely add it to this pr if the mod to the normal gateway is okay

### CODE REVIEW

**Review by bitfl0wer — COMMENTED** [review]
[// Note: The tungstenite backend handles close codes as messages, while the ws_stream_wasm one handles them differently.](https://github.com/polyphony-chat/chorus/blob/0c1cdf0f48aeff75de5e37f41b3aa98c0964c288/src/voice/gateway/gateway.rs#L156-L159)

Since I have seen this comment in multiple files now: Would it perhaps be possible and feasible to convert wasm-stream and tungstenite messages into the same type? that way, we would not have to differentiate between the two in multiple files

**Comment by kozabrada123** [comment]
That's how we used to do it; probably no, unless we have another task that just listens for ws_stream_wasm errors

**Comment by kozabrada123** [comment]
How the messages are is represented currently: non error messages from tungstenite and ws_stream_wasm can both be `RawGatewayMessage`. `GatewayCommunication` are all tungstenite messages

**Comment by bitfl0wer** [comment]
> That's how we used to do it; probably no, unless we have another task that just listens for ws_stream_wasm errors

I meaaaan, that could work!

**Comment by kozabrada123** [comment]
I think this is nicer
also, multiple files? they are twice in gateway.rs, and then in voice/gateway.rs (which is basically a copy of the former)

**Review by bitfl0wer — COMMENTED** [review]
I like these changes! My only issue with them would be what I already mentioned, but other than that it looks great!

**Pull request merged**
