### PR TITLE
Add serde impl for DateTime<Utc> from a string

### PR DESCRIPTION
**Pull request by Quat3rnion**
- Added a modified version of chrono's ts_seconds and ts_seconds_option that serialize and deserializes timestamps from strings.  
- Changes the RegisterConfiguration::default_rights field to actually be the Rights bitflag object.
- A few other small changes in support of the backend feature

### CODE REVIEW

**Comment by kozabrada123** [comment]
Thanks, I'll review this later today when I have time

**Comment by kozabrada123** [comment]
Looking at the tests though, seems there might a deserialization error in some (Ready?) gateway events

**Comment by kozabrada123** [comment]
I'm sorry, I think you might've misunderstood; Discord uses ISO8601 timestamps as string (e. g. "2024-01-02T13:18:46.923000+00:00"), not unix epoch timestamps as strings
Not parsing them as `DateTime`s was just an issue of not setting the right type, not needing a special serde implementation

**Comment by Quat3rnion** [comment]
Oh, I definitely misunderstood.  I guess I missed the 'iso' in your message.  I'll go ahead and close this and revert that stuff

**Comment by kozabrada123** [comment]
Sorry about that, looks like I made you do a bunch of work for nothing :woozy_face:

**Comment by kozabrada123** [comment]
Actully, funny thing is Discord **does** use this type of timestamps for one specific thing, so this implementation is useful, just not for those types. The place in question is literally one ratelimit header, [X-RateLimit-Reset](https://docs.discord.sex/topics/rate-limits#rate-limit-header-examples)

**Pull request closed without merging**
