### PR TITLE
Event and Eventtype

### PR DESCRIPTION
**Pull request by bitfl0wer**
I feel like these two Enums should be part of a library like this one, so I added them. :3c

### CODE REVIEW

**Comment by kozabrada123** [comment]
Hmmm, I originally avoided such an enum in our gateway implementation, since it will almost always be incomplete and adding new variants would be a breaking change to our api

**Comment by kozabrada123** [comment]
I think a solution to this would be to annotate both with [`#[non_exhaustive]`](https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute)

**Comment by bitfl0wer** [comment]
Closing this. The reason I haven't merged this right away was because I also contemplated whether this would be a good idea. The reason I needed the enum was for something in symfonia - so I just defined it there instead.

**Comment by kozabrada123** [comment]
Fair, considering the usage in Symfonia I also think it makes more sense to keep the enum there
When we add new events to `chorus`, Symfonia can also adopt them when it need emitters for them

**Pull request closed without merging**
